general:
steps:
gctsDeploy:
host: "https://tst.opensap.consarea.com:44300"
client: "100"
abapCredentialsId: "K0EMAR0Y_id"
repository: "k0emar0y-workbench"
remoteRepositoryURL: "https://github.com/K0EMAR0Y/workbench"
role: "SOURCE"
vSID: "K0E"
verbose: true
type: "GITHUB"
rollback: false
